# Generated by Django 5.0.6 on 2024-06-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_rename_userprofile_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesmodel',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('medium', 'Medium'), ('advanced', 'Advanced'), ('human_calculator', 'Human Calculator')], default='beginner', max_length=20),
        ),
    ]
